In [1]:
import torch
import pandas as np
import pandas as pd
import matplotlib.pyplot as plt

print(torch.__version__)

2.0.0


# Introduction to Tensors


## Creating tensors

### SCALAR


In [2]:
#scalar
scalar = torch.tensor(7)
scalar



tensor(7)

In [3]:
#dimension
scalar.ndim

0

In [4]:
#get tensor back as python int
scalar.item()

7

### VECTOR

In [5]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

### MATRIX

In [8]:
matrix = torch.tensor([[7,8],
                       [6,5]])
matrix

tensor([[7, 8],
        [6, 5]])

In [9]:
matrix[0]

tensor([7, 8])

### TENSOR

In [10]:
tensor = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
tensor


tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [11]:
tensor.ndim

3

In [12]:
tensor.shape

torch.Size([1, 3, 3])

## Random tensors

### Creating random tensors

In [13]:
#create a tensor with 3 rows and 4 columns
random_tensor = torch.rand(3,4) #rand creates a tensor in the range of 0 to 1
random_tensor

tensor([[0.2945, 0.6034, 0.6568, 0.9516],
        [0.5850, 0.1804, 0.2347, 0.4958],
        [0.0412, 0.1573, 0.2614, 0.7617]])

In [14]:
random_tensor.ndim

2

In [15]:
#create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3))  #height, width, color channels(RGB)
print('shape:',random_image_size_tensor.shape)
print('dimensions:',random_image_size_tensor.ndim)

shape: torch.Size([224, 224, 3])
dimensions: 3


### ZEROS and ONES tensors

In [16]:
# create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [17]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [18]:
# create a tensor of all ones
ones = torch.zeros(3,4)
ones

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
ones.dtype

torch.float32

### creating a range of tensors and tensors-like

In [20]:
# use torch.range
one_to_ten=torch.arange(0,10)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
#creating tensors like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

**Note:** Tensors datatypes is one of the 3 big issues with PyTorch and deep learling
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [22]:
#float32 tensors
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None, #what datatype is the tensor(e.g. float 32 or float 16)
                               device=None, #what device is your tensor on
                               requires_grad=False) #wheter or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [23]:
float_32_tensor.dtype

torch.float32

### transforming float 32 tensor to float 16 tensor

In [24]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [25]:
(float_16_tensor*float_32_tensor).dtype

torch.float32

### Getting information from tensors

1. Tensors not right datatype          = tensor.dtype
2. Tensors not right shape             = tensor.shape
3. Tensors not on the right device     = tensor.device

In [26]:
#create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.2541, 0.1253, 0.6007, 0.1168],
        [0.5740, 0.8694, 0.8594, 0.7899],
        [0.0433, 0.6329, 0.0387, 0.2010]])

In [27]:
print('dtype:',some_tensor.dtype)
print('shape:',some_tensor.shape, 'or size:', some_tensor.size())
print('device:',some_tensor.device)

dtype: torch.float32
shape: torch.Size([3, 4]) or size: torch.Size([3, 4])
device: cpu


## Manipulating Tensors (tensor operations)
Tensor operations include:
* Addition
* Subtraction
* Multiplication
* Division
* Matrix multiplication

In [28]:
#create tensor
tensor = torch.tensor([1,2,3])

In [29]:
#addition
tensor+10

tensor([11, 12, 13])

In [30]:
#Subtraction
tensor-10

tensor([-9, -8, -7])

In [31]:
#Multiplication
tensor*2

tensor([2, 4, 6])

In [32]:
#Division
tensor/2

tensor([0.5000, 1.0000, 1.5000])

In [33]:
#Matrix multiplication
tensor * torch.tensor([10,100,1000])

tensor([  10,  200, 3000])

In [34]:
#try out pytorch in-built functions
print('torch.mul:',torch.mul(tensor,10))
print('torch.add:',torch.add(tensor,5))

torch.mul: tensor([10, 20, 30])
torch.add: tensor([6, 7, 8])


### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning

1. Element-wise multiplication
2. Matrix multiplication (dot product)


1. The inner dimensions must match:
  * (3, 2) @ (3, 2) won't work
  * (2, 3) @ (3, 2) will work
  * (3, 2) @ (2, 3) will work

2. The resulting matrix has the shape of the outer dimensions:
  * (2, 3) @ (3, 2) -> (2, 2)
  * (3, 2) @ (2, 3) -> (3, 3)

Note: "@" in Python is the symbol for matrix multiplication.

Resource: You can see all of the rules for matrix multiplication using torch.matmul() in the PyTorch documentation.

link: http://matrixmultiplication.xyz/

In [35]:
#Element wise multiplication
tensor*tensor

tensor([1, 4, 9])

In [36]:
#Matrix multiplication
torch.matmul(tensor,tensor)
#OR
tensor @ tensor

tensor(14)

## One of the most common errors in deep learning: shape errors

In [37]:
# shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

torch.mm(tensor_A,tensor_B.T) #torch.mm is the same thing as torch.matmul


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### Transpose

In [38]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [39]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

## Finding the min, max, mean, sum etc...**(tensor aggregation)**

In [40]:
#create tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [41]:
#find the MIN
torch.min(x), x.min()

(tensor(0), tensor(0))

In [42]:
# find the MAX
torch.max(x),x.max()

(tensor(90), tensor(90))

In [43]:
#find the mean
torch.mean(x.type(torch.float32)),   x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [44]:
#find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [45]:
#finding the positional min and max(the index)
print(x)
print('min: ',torch.argmin(x))

print('max: ',torch.argmax(x))

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
min:  tensor(0)
max:  tensor(9)


## Reshaping, stacking, squeezing and unsqueezing

Often times you'll want to reshape or change the dimensions of your tensors without actually changing the values inside them.

To do so, some popular methods are:

| Method | One-line description |
| ----- | ----- |
| [`torch.reshape(input, shape)`](https://pytorch.org/docs/stable/generated/torch.reshape.html#torch.reshape) | Reshapes `input` to `shape` (if compatible), can also use `torch.Tensor.reshape()`. |
| [`torch.Tensor.view(shape)`](https://pytorch.org/docs/stable/generated/torch.Tensor.view.html) | Returns a view of the original tensor in a different `shape` but shares the same data as the original tensor. |
| [`torch.stack(tensors, dim=0)`](https://pytorch.org/docs/1.9.1/generated/torch.stack.html) | Concatenates a sequence of `tensors` along a new dimension (`dim`), all `tensors` must be same size. |
| [`torch.squeeze(input)`](https://pytorch.org/docs/stable/generated/torch.squeeze.html) | Squeezes `input` to remove all the dimenions with value `1`. |
| [`torch.unsqueeze(input, dim)`](https://pytorch.org/docs/1.9.1/generated/torch.unsqueeze.html) | Returns `input` with a dimension value of `1` added at `dim`. |
| [`torch.permute(input, dims)`](https://pytorch.org/docs/stable/generated/torch.permute.html) | Returns a *view* of the original `input` with its dimensions permuted (rearranged) to `dims`. |

Why do any of these?

Because deep learning models (neural networks) are all about manipulating tensors in some way. And because of the rules of matrix multiplication, if you've got shape mismatches, you'll run into errors. These methods help you make the right elements of your tensors are mixing with the right elements of other tensors.

Let's try them out.

First, we'll create a tensor.


In [46]:
#create tensor
import torch
x = torch.arange(1,11)
x,x.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), torch.Size([10]))

In [47]:
#RESHAPE -> add extra dimension
x_reshaped = x.reshape(5,2)
x_reshaped, x_reshaped.shape

(tensor([[ 1,  2],
         [ 3,  4],
         [ 5,  6],
         [ 7,  8],
         [ 9, 10]]),
 torch.Size([5, 2]))

In [48]:
#VIEW  -> change the view (does NOT change the data, it's just a view)
z = x.view(2,5)
z, z.shape

(tensor([[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]]),
 torch.Size([2, 5]))

In [49]:
# changing z changes x (because a view of a tensor shares the same memory as the original)
z[:,0]=00
z,x

(tensor([[ 0,  2,  3,  4,  5],
         [ 0,  7,  8,  9, 10]]),
 tensor([ 0,  2,  3,  4,  5,  0,  7,  8,  9, 10]))

In [50]:
#STACK  -> stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[ 0,  2,  3,  4,  5,  0,  7,  8,  9, 10],
        [ 0,  2,  3,  4,  5,  0,  7,  8,  9, 10],
        [ 0,  2,  3,  4,  5,  0,  7,  8,  9, 10],
        [ 0,  2,  3,  4,  5,  0,  7,  8,  9, 10]])

In [51]:
#STACK  -> stack tensors side to side of each other
y_stacked = torch.stack([x,x,x,x],dim=1)
y_stacked

tensor([[ 0,  0,  0,  0],
        [ 2,  2,  2,  2],
        [ 3,  3,  3,  3],
        [ 4,  4,  4,  4],
        [ 5,  5,  5,  5],
        [ 0,  0,  0,  0],
        [ 7,  7,  7,  7],
        [ 8,  8,  8,  8],
        [ 9,  9,  9,  9],
        [10, 10, 10, 10]])

In [52]:
#SQUEEZE -> remove a dimension
s =torch.arange(0,10).reshape(1,10)
print(s, s.shape)
s = s.squeeze()
#remove the dimensions that have only 1     shape = ([1,10])->([10])
print('\nsquezed tensor: ',s,'\n shape: ',s.shape)



tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]) torch.Size([1, 10])

squezed tensor:  tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) 
 shape:  torch.Size([10])


In [53]:
#UNSQUEEZE -> add a dimension
u =torch.arange(0,10)
print('horizontal: ',u.unsqueeze(0),u.unsqueeze(0).shape)
print('vertical: \n', u.unsqueeze(1),u.unsqueeze(1).shape)

horizontal:  tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]) torch.Size([1, 10])
vertical: 
 tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]]) torch.Size([10, 1])


In [54]:
#PERMUTE -> rearranges the dimensions of a target tensor in a specified order

x_original = torch.rand(size=(224,224,3))                                   #[height, width, color channels]
x_permuted=x_original.permute(2,0,1)  # -> put the color channel to be the first dim -> [color channels, height, width]
print('before: ',x_original.shape,'\nafter:  ',x_permuted.shape)

before:  torch.Size([224, 224, 3]) 
after:   torch.Size([3, 224, 224])


## Indexing (selecting data from tensors)

In [55]:
#create tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [56]:
tensor=torch.stack([x,x*2,x**2])
tensor

tensor([[[[ 1,  2,  3],
          [ 4,  5,  6],
          [ 7,  8,  9]]],


        [[[ 2,  4,  6],
          [ 8, 10, 12],
          [14, 16, 18]]],


        [[[ 1,  4,  9],
          [16, 25, 36],
          [49, 64, 81]]]])

In [57]:
tensor[0,0,1,2].item()

6

## PyTorch tensors and NumPy

In [58]:
# Numpy array to tensor
import torch
import numpy as np
array = np.arange(1,8)
tensor = torch.from_numpy(array)
array,tensor

(array([1, 2, 3, 4, 5, 6, 7]), tensor([1, 2, 3, 4, 5, 6, 7]))

In [59]:
#Tensor to numpy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
numpy_tensor,tensor

(array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 tensor([1., 1., 1., 1., 1., 1., 1.]))

## Reproducibility (trying to take random out of random)

In [60]:
#MANUAL SEED
torch.manual_seed(seed=42)
random_tensor = torch.rand(3,4)
torch.manual_seed(seed=42)
random_tensor2 = torch.rand(3,4)
print(random_tensor==random_tensor2,'\n so the tensors are equals')


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]]) 
 so the tensors are equals


## Running tensors on GPUs (and making faster computations)

In [61]:
!nvidia-smi

Mon Jul 31 18:53:01 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.161.03   Driver Version: 470.161.03   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   30C    P0    25W / 250W |      0MiB / 16280MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [62]:
# Check for GPU
torch.cuda.is_available()

True

### set the device automatic

In [63]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [64]:
# Count number of devices
torch.cuda.device_count()

1

### Putting tensors (and models) on the GPU


In [65]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

###  Moving tensors back to the CPU

In [66]:
# Instead, copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

## Exercises

In [67]:
a=torch.tensor([1,2,4,5,6,7,7])
b=torch.randint(0,8,(1,7))

In [68]:
torch.matmul(a,b.T)

tensor([170])

In [69]:
a@b.T

tensor([170])

In [70]:
a

tensor([1, 2, 4, 5, 6, 7, 7])

In [71]:
a=a.to(device)
a

tensor([1, 2, 4, 5, 6, 7, 7], device='cuda:0')

In [72]:
a.cpu().numpy()

array([1, 2, 4, 5, 6, 7, 7])

In [73]:
(a+(b.to(device))).argmax()

tensor(5, device='cuda:0')

In [74]:
b

tensor([[2, 2, 7, 4, 3, 7, 7]])

In [75]:
tensor=torch.rand(size=(1,1,1,1,1,10))

In [76]:
tensor.size()

torch.Size([1, 1, 1, 1, 1, 10])

In [77]:
tensor.size()

torch.Size([1, 1, 1, 1, 1, 10])

In [78]:
tensor.squeeze().unsqueeze(0).unsqueeze(0).cpu()

tensor([[[0.6274, 0.2696, 0.4414, 0.2969, 0.8317, 0.1053, 0.2695, 0.3588,
          0.1994, 0.5472]]])